createOrReplace

	table Customer
		lineageTag: 75d7213a-419f-486d-8e03-185c45146d88

		/// Unique internal identifier for the customer
		column CustomerKey
			dataType: int64
			isHidden
			formatString: 0
			isAvailableInMdx: false
			lineageTag: 7c537edd-69ee-4ea2-9e6b-061697df4db0
			summarizeBy: none
			sourceColumn: CustomerKey

			annotation SummarizationSetBy = Automatic

			annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MARK_PRIMARY_KEYS"]}

		/// Customer's gender
		column Gender
			dataType: string
			lineageTag: 0dbd41b5-6677-4af4-b2b7-7919a1535e4f
			summarizeBy: none
			sourceColumn: Gender

			annotation SummarizationSetBy = Automatic

		/// Customer's full name
		column Name
			dataType: string
			lineageTag: 97119290-f7b6-4ac5-be1b-cdeec1096218
			summarizeBy: none
			sourceColumn: Name

			annotation SummarizationSetBy = Automatic

		/// Customer's street address
		column Address
			dataType: string
			lineageTag: 67fe9164-a135-411a-99e9-75c63593d529
			summarizeBy: none
			sourceColumn: Address

			annotation SummarizationSetBy = Automatic

		/// City where the customer resides
		column City
			dataType: string
			lineageTag: b3d604cb-dbc7-49d1-8b77-fb2d8c3d27b0
			dataCategory: City
			summarizeBy: none
			sourceColumn: City

			annotation SummarizationSetBy = Automatic

		/// Abbreviated state or province code
		column 'State Code'
			dataType: string
			lineageTag: 5b3e667a-b660-47a2-b37a-6f8fc0b005aa
			summarizeBy: none
			sourceColumn: State Code

			annotation SummarizationSetBy = Automatic

		/// State or province where the customer resides
		column State
			dataType: string
			lineageTag: 866e9eeb-60e7-4f34-a758-699b2f08d6f5
			summarizeBy: none
			sourceColumn: State

			annotation SummarizationSetBy = Automatic

		/// Postal or ZIP code for the customer's address
		column 'Zip Code'
			dataType: string
			lineageTag: a52eaa3b-91b6-4d76-9b98-9efe5ec553aa
			summarizeBy: none
			sourceColumn: Zip Code

			annotation SummarizationSetBy = Automatic

		/// ISO country code for the customer's location
		column 'Country Code'
			dataType: string
			lineageTag: a96c9024-09b2-471e-bffa-8c045ec3c07e
			dataCategory: Caption
			summarizeBy: none
			sourceColumn: Country Code

			annotation SummarizationSetBy = Automatic

		/// Country where the customer resides
		column Country
			dataType: string
			lineageTag: 2e529497-a682-465f-bd24-9563ce148b50
			dataCategory: Country
			summarizeBy: none
			sourceColumn: Country

			annotation SummarizationSetBy = Automatic

		/// Continent where the customer is located
		column Continent
			dataType: string
			lineageTag: 98a38c06-5477-41f6-9faa-c6b3d95d215b
			dataCategory: Continent
			summarizeBy: none
			sourceColumn: Continent

			annotation SummarizationSetBy = Automatic

		/// Customer's date of birth
		column Birthday
			dataType: dateTime
			formatString: Long Date
			lineageTag: da3e313f-fb00-4616-8e87-e2512d60a28b
			summarizeBy: none
			sourceColumn: Birthday

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		/// Customer's age in years
		column Age
			dataType: int64
			formatString: 0
			lineageTag: baeb7390-137d-48e5-a419-00d4960d2652
			summarizeBy: none
			sourceColumn: Age

			annotation SummarizationSetBy = Automatic

		partition Customer = m
			mode: import
			source =
					let
					    Source = Sql.Databases(Server),
					    Database = Source{[Name=Database]}[Data],
					    dbo_Customer = Database{[Schema="dbo",Item="Customer"]}[Data],
					    #"Filtered Rows" = Table.SelectRows(dbo_Customer, each ([Country] <> "Canada" and [Country] <> "Germany" and [Country] <> "Netherlands"))
					in
					    #"Filtered Rows"

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	table Product
		lineageTag: 30d51099-9182-4805-8640-4e935922ae23

		/// Unique identifier for each product in the catalog
		column ProductKey
			dataType: int64
			isHidden
			formatString: 0
			isAvailableInMdx: false
			lineageTag: 74400d17-e1b6-456e-8fa2-2850ff493aad
			summarizeBy: none
			sourceColumn: ProductKey

			annotation SummarizationSetBy = Automatic

			annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MARK_PRIMARY_KEYS"]}

		/// Product SKU or stock keeping unit code
		column 'Product Code'
			dataType: string
			lineageTag: 5e28d45b-fa8a-4e5e-85c2-722334c22029
			summarizeBy: none
			sourceColumn: Product Code

			annotation SummarizationSetBy = Automatic

		/// Full descriptive name of the product
		column 'Product Name'
			dataType: string
			lineageTag: 04da1f3c-4a56-4565-93fd-5368cdf3c421
			summarizeBy: none
			sourceColumn: Product Name

			annotation SummarizationSetBy = Automatic

		/// Company that manufactures the product
		column Manufacturer
			dataType: string
			lineageTag: 4a34302f-ec56-498f-a39b-43978fc51870
			summarizeBy: none
			sourceColumn: Manufacturer

			annotation SummarizationSetBy = Automatic

		/// Brand name under which the product is sold
		column Brand
			dataType: string
			lineageTag: f10c6734-9804-49c9-9f42-a7ff2e3be92c
			summarizeBy: none
			sourceColumn: Brand

			annotation SummarizationSetBy = Automatic

		/// Primary color of the product
		column Color
			dataType: string
			lineageTag: 0688a4f3-f0a4-4de4-bbe6-e598488fc55f
			summarizeBy: none
			sourceColumn: Color

			annotation SummarizationSetBy = Automatic

		/// Unit of measurement for product weight (e.g., kg, lbs)
		column 'Weight Unit Measure'
			dataType: string
			lineageTag: 04b144e6-7d82-4999-b044-a4b7dda920f6
			summarizeBy: none
			sourceColumn: Weight Unit Measure

			annotation SummarizationSetBy = Automatic

		/// Weight of the product in the specified unit measure
		column Weight
			dataType: decimal
			lineageTag: 848c4e72-c81f-4621-b6fc-bb75d98d6d24
			summarizeBy: none
			sourceColumn: Weight

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"isGeneralNumber":true}

		/// Cost per unit paid to acquire or manufacture the product
		column 'Unit Cost'
			dataType: decimal
			formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
			lineageTag: 7a232987-c447-44c3-ba07-2e3ca7f4d779
			summarizeBy: none
			sourceColumn: Unit Cost

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"currencyCulture":"en-US"}

		/// Selling price per unit for the product
		column 'Unit Price'
			dataType: decimal
			formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
			lineageTag: e38f4725-db48-451a-8c1d-5dd58b853797
			summarizeBy: none
			sourceColumn: Unit Price

			annotation SummarizationSetBy = Automatic

			annotation PBI_FormatHint = {"currencyCulture":"en-US"}

		/// Numeric code identifying the product subcategory
		column 'Subcategory Code'
			dataType: int64
			formatString: 0
			lineageTag: 97799974-e173-480f-8b7b-c409d158f3e0
			summarizeBy: none
			sourceColumn: Subcategory Code

			annotation SummarizationSetBy = Automatic

		/// Product subcategory grouping (e.g., Laptops, Tablets)
		column Subcategory
			dataType: string
			lineageTag: 742861f7-3ef5-4b9f-a1dd-85a6a95e7839
			summarizeBy: none
			sourceColumn: Subcategory

			annotation SummarizationSetBy = Automatic

		/// Numeric code identifying the product category
		column 'Category Code'
			dataType: int64
			formatString: 0
			lineageTag: 0b2dcb3c-dc9f-47c5-8f4a-cc41aa2aeb58
			summarizeBy: none
			sourceColumn: Category Code

			annotation SummarizationSetBy = Automatic

		/// High-level product category (e.g., Electronics, Home Goods)
		column Category
			dataType: string
			lineageTag: 5d64bbfb-0699-4dc9-a26a-8b243b065003
			summarizeBy: none
			sourceColumn: Category

			annotation SummarizationSetBy = Automatic

		partition Product = m
			mode: import
			source =
					let
					    Source = Sql.Databases(Server),
					    Database = Source{[Name=Database]}[Data],
					    dbo_Product = Database{[Schema="dbo",Item="Product"]}[Data],
					    #"Filtered Rows" = Table.SelectRows(dbo_Product, each ([Color] <> "Blue" and [Color] <> "Gold" and [Color] <> "Green" and [Color] <> "Pink" and [Color] <> "Red" and [Color] <> "Silver" and [Color] <> "White"))
					in
					    #"Filtered Rows"

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

	table Store
		lineageTag: 9b30a64f-cbab-4834-9105-f6e8e131c88b

		/// Unique internal identifier for the store
		column StoreKey
			dataType: int64
			isHidden
			formatString: 0
			isAvailableInMdx: false
			lineageTag: 516eccd0-65a9-41cc-b24b-e3286d993d46
			summarizeBy: none
			sourceColumn: StoreKey

			annotation SummarizationSetBy = Automatic

			annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["MARK_PRIMARY_KEYS"]}

		/// Numeric store code used in legacy systems and integrations
		column 'Store Code'
			dataType: int64
			formatString: 0
			lineageTag: c9be2ed7-d1d9-49d9-b018-180d1672f40f
			summarizeBy: none
			sourceColumn: Store Code

			annotation SummarizationSetBy = Automatic

		/// Country where the store is located
		column Country
			dataType: string
			lineageTag: 795d4db4-397d-48dc-8702-817e604fb35e
			dataCategory: Country
			summarizeBy: none
			sourceColumn: Country

			annotation SummarizationSetBy = Automatic

		/// State or region where the store is located
		column State
			dataType: string
			lineageTag: a4958153-34f2-423b-998d-e835f4d91599
			summarizeBy: none
			sourceColumn: State

			annotation SummarizationSetBy = Automatic

		/// Official store name
		column Name
			dataType: string
			lineageTag: b8cbed21-825d-441b-8f4f-601fef630155
			summarizeBy: none
			sourceColumn: Name

			annotation SummarizationSetBy = Automatic

		/// Store floor area, in square meters
		column 'Square Meters'
			dataType: int64
			formatString: 0
			lineageTag: 11b7c8c3-82fd-4381-9284-7a6938fd00b5
			summarizeBy: none
			sourceColumn: Square Meters

			annotation SummarizationSetBy = Automatic

		/// Date when the store first opened (business date)
		column 'Open Date'
			dataType: dateTime
			formatString: dd/mm/yyyy
			lineageTag: 1565c522-323a-458e-b976-b16c41bf40de
			summarizeBy: none
			sourceColumn: Open Date

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		/// Date when the store closed (if applicable)
		column 'Close Date'
			dataType: dateTime
			formatString: dd/mm/yyyy
			lineageTag: 06d5cabc-5bb7-43e9-a691-78166be6479c
			summarizeBy: none
			sourceColumn: Close Date

			annotation SummarizationSetBy = Automatic

			annotation UnderlyingDateTimeDataType = Date

		/// Current operational status of the store (e.g., Open, Closed)
		column Status
			dataType: string
			lineageTag: be28b028-fb39-47b2-9742-98e0e40ade07
			summarizeBy: none
			sourceColumn: Status

			annotation SummarizationSetBy = Automatic

		partition Store = m
			mode: import
			source =
					let
					    Source = Sql.Databases(Server),
					    Database = Source{[Name=Database]}[Data],
					    dbo_Store = Database{[Schema="dbo",Item="Store"]}[Data]
					in
					    dbo_Store

		annotation PBI_ResultType = Table

		annotation PBI_NavigationStepName = Navigation

		annotation BestPracticeAnalyzer_IgnoreRules = {"RuleIDs":["OBJECTS_WITH_NO_DESCRIPTION"]}

